version: '3'

dotenv: ['.env']

# Prerequisites for this taskfile to run:
# - https://github.com/helm/chart-releaser
# - https://github.com/norwoodj/helm-docs
# - https://github.com/pawamoy/git-changelog

tasks:
  package:
    desc: Package the Helm Chart (Don't forget to bump proper version)
    cmds:
      - task: readme
      - task: changelog
      - rm -Rf .cr-release-packages/
      - cr package

  upload:
    desc: Uploads the Helm Chart as release to GitHub
    cmds:
      - cr upload -o $GITHUB_USERNAME -r $CHART_NAME -t $GITHUB_TOKEN

  index:
    desc: Creates or updates the index file and pushes it to the default github pages branch
    cmds:
      - cr index -o $GITHUB_USERNAME -r $CHART_NAME -t $GITHUB_TOKEN -i . --push
      - rm index.yaml

  publish:
    desc: Execute all steps for a Helm Chart deployment on GitHub-Pages (Don't forget to bump proper version)
    cmds:
      - task: package
      - task: upload
      - task: index

  readme:
    desc: Build readme
    cmds:
      - helm-docs

  changelog:
    desc: Generate Changelog
    cmds:
      - rm -f CHANGELOG.md
      - git-changelog -o CHANGELOG.md -c conventional -t keepachangelog .
